### ISSUE TITLE
Miner Registry

### ISSUE THREAD

**Issue by francisypl** [francisypl/mineranker#11]
Create endpoints where:
GET `/miners?q=<miner_name>`
- list all miners with names that contain the <miner_name>

GET `/miners`
- list all miners

POST `/miners`
- Register a miner
- Create a collection on the database for this miner. The collection name would be the `name` of the miner.

body
```json
{
    "name": "hacker_news",
    "description": "The official hacker news miner. Here you can find updates to SE topics.",
}
```

PATCH `/miners/<miner_id>`
- only the `description` can be changed

Miner Model:
```json
{
    "id": "<id of miner>",
    "name": "<name of the miner | unique>",
    "description": "<description of what this miner's content>",
}
```

**Comment by abdulbasitkay** [comment]
I am trying to work on this issue. what is the model of rankers?

**Comment by francisypl** [comment]
@abdulbasitkay awesome!!

The model of the `rankers` is detailed under [Ranker Architechture](https://github.com/francisypl/mineranker#ranker-architecture). Don't worry about the `user` property for now since we are not clear on how to authenticate users or even have authentication. A ranker should have a `filter` property and a `sort` property.

**Comment by francisypl** [comment]
Feel free to join our [slack](https://software-daily-slack.herokuapp.com/) you can reach me there too.

**Comment by abdulbasitkay** [comment]
am on slack `@abulkay`

**Comment by francisypl** [comment]
Hey @abdulbasitkay I updated the requirements a bit. Let me know if you have any questions.

**Comment by abdulbasitkay** [comment]
@francisypl makes sense, will contact if I have any question.
