### ISSUE TITLE
Figure out kinks with Heroku

### ISSUE THREAD

**Issue by francisypl** [francisypl/mineranker#5]
Not sure how heroku builds node apps.
It seems to run `npm run build` first but heroku can't resolve the webpack dependency.
For now I made `npm run build` to just echo a message. It goes straight to `npm run start`.

We have to figure out a way to let heroku build the app when we deploy it.

**Comment by msdinit** [comment]
Hi,
I believe my pull request #17 should resolve issues with heroku (at least the app builds and runs on my deploy)
Since `yarn.lock` is in the git, heroku will now use only yarn to build and deploy the app

**Comment by francisypl** [comment]
Cool thanks - that worked merging the PR now 👍

**Comment by msdinit** [comment]
Cool, glad to help!
